export const ADD_UNITS = 'ADD_UNITS';
export const UNITS_LOADING = 'UNITS_LOADING';
export const UNITS_FAILED = 'UNITS_FAILED';

export const ADD_UNIT = 'ADD_UNIT';

export const ADD_WORKSHOPS = 'ADD_WORKSHOPS';
export const WORKSHOPS_LOADING = 'WORKSHOPS_LOADING';
export const WORKSHOPS_FAILED = 'WORKSHOPS_FAILED';

export const ADD_CALENDARS = 'ADD_CALENDARS';
export const CALENDARS_LOADING = 'CALENDARS_LOADING';
export const CALENDARS_FAILED = 'CALENDARS_FAILED';

export const ADD_FEEDBACK = 'ADD_FEEDBACK';