export const ADD_UNITS = 'ADD_UNITS';
export const UNITS_LOADING = 'UNITS_LOADING';
export const UNITS_FAILED = 'UNITS_FAILED';

export const ADD_UNIT = 'ADD_UNIT';

export const ADD_WORKSHOPS = 'ADD_WORKSHOPS';
export const WORKSHOPS_LOADING = 'WORKSHOPS_LOADING';
export const WORKSHOPS_FAILED = 'WORKSHOPS_FAILED';

export const ADD_CALENDARS = 'ADD_CALENDARS';
export const CALENDARS_LOADING = 'CALENDARS_LOADING';
export const CALENDARS_FAILED = 'CALENDARS_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const ADD_USER = 'ADD_USER';
//export const USER_SUCCESS = 'USER_SUCCESS';
//export const USER_FAILURE = 'USER_FAILURE';

export const ADD_CONTACT = 'ADD_CONTACT';
/* export const CONTACT_SUCCESS = 'CONTACT_SUCCESS';
export const CONTACT_FAILURE = 'CONTACT_FAILURE'; */